DELETE FROM ofUser where username='helen1%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen1%i1xq3w6q5kw', 'test', NULL, 'helen1%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen2%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen2%i1xq3w6q5kw', 'test', NULL, 'helen2%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen3%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen3%i1xq3w6q5kw', 'test', NULL, 'helen3%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen4%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen4%i1xq3w6q5kw', 'test', NULL, 'helen4%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen5%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen5%i1xq3w6q5kw', 'test', NULL, 'helen5%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen6%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen6%i1xq3w6q5kw', 'test', NULL, 'helen6%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen7%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen7%i1xq3w6q5kw', 'test', NULL, 'helen7%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen8%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen8%i1xq3w6q5kw', 'test', NULL, 'helen8%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen9%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen9%i1xq3w6q5kw', 'test', NULL, 'helen9%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen10%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen10%i1xq3w6q5kw', 'test', NULL, 'helen10%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen11%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen11%i1xq3w6q5kw', 'test', NULL, 'helen11%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen12%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen12%i1xq3w6q5kw', 'test', NULL, 'helen12%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen13%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen13%i1xq3w6q5kw', 'test', NULL, 'helen13%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen14%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen14%i1xq3w6q5kw', 'test', NULL, 'helen14%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen15%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen15%i1xq3w6q5kw', 'test', NULL, 'helen15%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen16%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen16%i1xq3w6q5kw', 'test', NULL, 'helen16%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen17%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen17%i1xq3w6q5kw', 'test', NULL, 'helen17%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen18%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen18%i1xq3w6q5kw', 'test', NULL, 'helen18%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen19%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen19%i1xq3w6q5kw', 'test', NULL, 'helen19%i1xq3w6q5kw', 'email', '0', '0');
DELETE FROM ofUser where username='helen20%i1xq3w6q5kw';
INSERT INTO ofUser ( username , plainPassword, encryptedPassword, name, email, creationDate, modificationDate) VALUES ('helen20%i1xq3w6q5kw', 'test', NULL, 'helen20%i1xq3w6q5kw', 'email', '0', '0');
